name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip modules
        run: |
          unzip -o app.zip -d .
          unzip -o data.zip -d .
          unzip -o domain.zip -d .
          unzip -o scripts.zip -d .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RohailsNoteBook-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
